sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t kdautrey/rpi-sonarr .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    TAG=$(date +"%d-%m-%y")
    docker tag kdautrey/rpi-sonarr kdautrey/rpi-sonarr:$TAG
    docker push kdautrey/rpi-sonarr:$TAG
    docker push kdautrey/rpi-sonarr
  fi
